// <auto-generated />
using MagicVilla_VillaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaApi.Migrations
{
    [DbContext(typeof(ApplicatonDbcontext))]
    [Migration("20250109112816_AddVillaTable")]
    partial class AddVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupency")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Connection was successfully established with the server, but then an error occurred duri",
                            ImageUrl = "Dummy",
                            Name = "First Villa",
                            Occupency = 130,
                            Rate = 104342125.0,
                            Sqft = 1024
                        },
                        new
                        {
                            Id = 2,
                            Description = "Connection was successfully established with the server, but then an error occurred duri",
                            ImageUrl = "Dummy",
                            Name = "Second Villa",
                            Occupency = 1430,
                            Rate = 104342125.0,
                            Sqft = 1024
                        },
                        new
                        {
                            Id = 3,
                            Description = "Connection was successfully established with the server, but then an error occurred duri",
                            ImageUrl = "Dummy",
                            Name = "Third Villa",
                            Occupency = 1530,
                            Rate = 1742125.0,
                            Sqft = 1024
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
